# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrance'), ('OUT', 'Exit')], max_length=200)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_date', models.DateTimeField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sensor')),
            ],
        ),
    ]
