# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='app.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
