# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20171008_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.AddField(
            model_name='movement',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
