# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='app.Space'),
        ),
    ]
